# Generated by Django 4.1.4 on 2022-12-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="asignee",
            new_name="assignee",
        ),
    ]
